"""Add application database constraints

Revision ID: c4d3f78efe46
Revises: 
Create Date: 2026-09-23 16:28:42.886552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4d3f78efe46'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'company',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=255),
               nullable=False)
    
    op.alter_column('applications', 'position',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column(
        'applications', 'status', existing_type=sa.VARCHAR(),nullable=False,
    )
    
    op.create_check_constraint('valid_application_status', 'applications',
                               "status IN ('applied', 'interview', 'offer', 'selected', 'rejected', 'ghosted')",)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'valid_application_status', 'applications', type_ ='check',
    )
    op.alter_column('applications', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('applications', 'position',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('applications', 'company',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
